version: '3.8'

services:
  database:
    container_name: lab4-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: university
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
